author: "Joseph Moniz <joseph.moniz@gmail.com>"
description: "The Option typeclass inspired by Scala's implementation and Haskell's Maybe monad. Option is a composable and more expressive alternative to things that may be null on absence of value.\n"
homepage: "https://github.com/JosephMoniz/dart-option"
name: "option"
version: "1.1.0"
dependencies: 
  concepts: 
    git: 
      ref: "5f84d2a4cdd7a7ecc2ecefdfdaa0e3b2fefb1f2f"
      url: "git@github.com:Andersmholmgren/dart-concepts.git"
dev_dependencies: 
  test: "any"
environment: 
  sdk: ">=1.8.0 <2.0.0"
