author: "Joseph Moniz <joseph.moniz@gmail.com>"
description: "The Option typeclass inspired by Scala's implementation and Haskell's Maybe monad. Option is a composable and more expressive alternative to things that may be null on absence of value.\n"
homepage: "https://github.com/JosephMoniz/dart-option"
name: "option"
version: "1.1.0"
dependencies: 
#  either: '^0.1.8'
  concepts: 
    path: "/Users/blah/dart/backlogio_acdart/gitbacklog_root/gissue_root/acdart_root/shelfish_root/thirdparty_core_root/dart-concepts"
dev_dependencies: 
  test: 'any'
environment:
  sdk: '>=1.8.0 <2.0.0'
